spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    url: jdbc:h2:tcp://localhost:1521/sa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 9091

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false